name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa uma vez por dia à meia-noite
  workflow_dispatch:  # Permite disparar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Passo 2: Gerar o arquivo .svg com a cobrinha
      - name: Generate Snake Animation
        uses: Platane/snk@v2  # Usando a versão estável
        with:
          github_user_name: gustavgallo
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Passo 3: Adicionar o arquivo gerado ao repositório
      - name: Commit SVG file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Add generated snake animation"
          git push

      # Passo 4: Fazer o upload do arquivo gerado para o GitHub Pages
      - name: Upload SVG to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/github-contribution-grid-snake.svg
