name: Generate Snake
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Snake
        uses: https://github.com/Platane/snk@9e15a9f3b9b7e1a0e0d8c  # Versão estável
        with:
          github_user_name: gustavgallo
          outputs: snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update snake" || echo "Sem mudanças"
          git push
