name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:       # permite disparar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2    # versão estável
        with:
          github_user_name: gustavgallo
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: actions/upload-pages-artifact@v4  
        with:
          path: dist/github-contribution-grid-snake.svg #vai fazer a cobrinha do github?
