name: Snake Garantido
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  gerar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v2
        with:
          github_user_name: gustavgallo
          outputs: github-contribution-grid-snake.svg
      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update snake" || echo "Sem mudanças"
          git push
